# Generated by Django 3.0.2 on 2020-01-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
