# Generated by Django 3.0.2 on 2020-01-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0006_cart_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='owner',
        ),
    ]
